# Generated by Django 3.0.3 on 2021-05-20 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0003_resource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_start', models.IntegerField(default=0)),
                ('pos_end', models.IntegerField(default=0)),
                ('node_uri', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='original_text_uri',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='TextRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_entity', to='db.Entity')),
                ('end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_entity', to='db.Entity')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_entity', to='db.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=500)),
                ('original_object_uri', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='markup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_markup', to='db.Markup'),
        ),
    ]
