# Generated by Django 3.0.3 on 2021-05-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210521_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='markup',
            name='ontology_uri',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
