# Generated by Django 3.0.3 on 2021-05-24 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0007_textrelation_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markup_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
