# Generated by Django 3.0.3 on 2021-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210524_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='', max_length=300),
        ),
    ]
